### ISSUE TITLE
webui is unusable on linux: double click on node doesn't open console

### ISSUE THREAD

**Issue by nosy** [GNS3/gns3-webclient-pack#15]
OS: Ubuntu 20.04
Client Pack: from unstable ppa 
Chrome/Firefox
https://launchpad.net/~gns3/+archive/ubuntu/unstable
Web UI : localhost:3080

And right click then type console doesn't work too.
Only web console works

```
xdg-open "gns3+telnet://127.0.0.1:5000/"
gio: gns3+telnet://127.0.0.1:5000/: The specified location is not supported

```
What console settings do i need to bind for double clicking on node and open gnome terminal for example?

**Comment by grossmj** [comment]
This has been fixed: https://github.com/GNS3/gns3-webclient-pack/issues/18#issuecomment-1200397013
