### ISSUE TITLE
Launching gns3-webclient-config on Mac OS Big sur fails

### ISSUE THREAD

**Issue by liftconfig** [GNS3/gns3-webclient-pack#19]
When launching gns3-webclient-config on Mac OS Big Sur 11.2.3, nothing happens. When going into the activity monitor the process is running at 100% cpu. The web client launcher is working with the Web GUI but there is no way to configure settings without the webclient configuration tool.

Webclient-pack: GNS3.WebClient.pack-1.0.0b3.dmg
GNS3 VM version: 2.2.20

**Comment by vittore** [comment]
+1
Tested with Chrome and Firefox

**Comment by eternalnerd** [comment]
+1

Big Sur 11.6

**Comment by grossmj** [comment]
Is the app in the `/Applications` folder when you launch it?

**Comment by grossmj** [comment]
@liftconfig @vittore @eternalnerd ? :)

**Comment by vittore** [comment]
Now it's works.

**Comment by grossmj** [comment]
I will probably have to remove the requirement of running the app from the `/Applications` folder: https://github.com/GNS3/gns3-webclient-pack/blob/e094efd63df4b504e4bb78cc85634aa4d8cca923/gns3_webclient_pack/main.py#L128L136

**Comment by ghost** [comment]
'+ 1 Ventura 13.1 (22C65)

**Comment by grossmj** [comment]
Please try with this version: https://sourceforge.net/projects/gns-3/files/Releases/WebClient/v1.0.0b4/GNS3-WebClient-pack-1.0.0b4.dmg/download

Thanks!

**Comment by ghost** [comment]
> Please try with this version: https://sourceforge.net/projects/gns-3/files/Releases/WebClient/v1.0.0b4/GNS3-WebClient-pack-1.0.0b4.dmg/download
> 
> Thanks!

This works. Thanks!
