### ISSUE TITLE
Slackware support

### ISSUE THREAD

**Issue by Eugene-Prokhorenko** [GNS3/gns3-webclient-pack#22]
No support for Slackware

bash-5.1$ sudo python3 -m pip install setup.py
ERROR: Could not find a version that satisfies the requirement setup.py (from versions: none)
ERROR: No matching distribution found for setup.py
bash-5.1$

**Comment by grossmj** [comment]
What Python version do you have?

**Comment by cristian-ciobanu** [comment]
I have tried also to manually install the client pack using pip on ArchLinux using the command above and the same error popped up. I'm using the latest Python 3 version 3.10.5

**_$ sudo python3 -m pip install setup.py
ERROR: Could not find a version that satisfies the requirement setup.py
ERROR: No matching distribution found for setup.py_**

Then I tried with the provided **install.sh** script and it worked fine. I see only some Linux distributions are supported and Slackware is not on the list

```
for distro_id in $ID $ID_LIKE; do
        case "$distro_id" in
                debian|ubuntu)
                        sudo apt-get install -y python3 python3-pyqt5 telnet vinagre virt-viewer wireshark
                        do_install
                        ;;
                arch|archlinux|manjaro)
                        sudo pacman -S python python-pyqt5 qt5-websockets vinagre virt-viewer wireshark-qt
                        do_install
                        ;;
                fedora)
                        sudo dnf install -y python3 python3-pyqt5 telnet vinagre virt-viewer wireshark-qt
                        do_install
                        ;;
                opensuse|suse)
                        sudo zypper install -y python3 python3-pyqt5 telnet vinagre virt-viewer wireshark-ui-qt
                        do_install
                        ;;
                #centos|CentOS|rhel)
                #       sudo yum install -y python3 PyQt5 telnet vinagre virt-viewer wireshark-gnome
                #       do_install
                #       ;;
                *)
                        continue
                        ;;
        esac
done
```

**Comment by grossmj** [comment]
> I have tried also to manually install the client pack using pip on ArchLinux using the command above and the same error popped up. I'm using the latest Python 3 version 3.10.5

Please can you tried to add these lines to setup.py and try again?

```
"Programming Language :: Python :: 3.9",
"Programming Language :: Python :: 3.10",
```

> Slackware is not on the list

I would be happy to add it, what is the command to install the required packages? `python3 python3-pyqt5 telnet vinagre virt-viewer wireshark-qt`

**Comment by cristian-ciobanu** [comment]
I tried this and the same error is displayed.

```
$ sudo python3 -m pip install setup.py
ERROR: Could not find a version that satisfies the requirement setup.py
ERROR: No matching distribution found for setup.py
```
I looked at the requirements.txt file and it does not specify a module and a version only the text **distro** on the first line

**Comment by grossmj** [comment]
@cristian-ciobanu 

I have pushed this https://github.com/GNS3/gns3-webclient-pack/commit/6a580254152b6b4df2d93eea7fd90c4aa8e3dc1a please can you try again? thanks
