### ISSUE TITLE
The console opens but the device turns off after few seconds

### ISSUE THREAD

**Issue by xdnroot** [GNS3/gns3-webclient-pack#24]
# Version Info
gns3-server: 2.2.33.1
gns3-webclient-pack:1.0.0b3

# Problem
When I try console using gns3-webclient-pack, the console putty opens but the device turns off after few seconds.
This behavior not happened when I use web console.
I use builtin VPC on GNS3.

Please check and provide the solution.
Thanks.

**Comment by grossmj** [comment]
Hi, what OS do you use and how have you install the webclient pack?
