### ISSUE TITLE
Package gns3-webclient-pack 1.0.0b4 is not published to Python package index repository

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-webclient-pack#29]
Please update the Pypi gns3-webclient-pack repository with the latest version 1.0.0b4. Currently version 1.0.0b3 is the latest one available.
https://pypi.org/project/gns3-webclient-pack/#history

**Comment by grossmj** [comment]
Thanks, I have published the missing package: https://pypi.org/project/gns3-webclient-pack/1.0.0b4/
