### ISSUE TITLE
gns3-webclient-pack installation error

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-webclient-pack#3]
I'm trying to install gns3-webclient-pack on ArchLinux using one of the two methods provided below but it fails with the following error:

**Collecting gns3-webclient-pack
  ERROR: Could not find a version that satisfies the requirement gns3-webclient-pack (from versions: none)
ERROR: No matching distribution found for gns3-webclient-pack**

**Linux (Pypi package)**
pip3 install gns3-webclient-pack

**Linux script installation**
wget -qO- https://raw.githubusercontent.com/GNS3/gns3-webclient-pack/master/install.sh | sh

**Comment by grossmj** [comment]
Sorry, our first beta hasn't been pushed on Pypi. We will release another one soon.

**Comment by grossmj** [comment]
Beta 2 has been released. This should work now. Thanks :)
