### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by diniz2010** [GNS3/gns3-webclient-pack#33]
Hello. I would like to ask if anyone has had difficulties with the following issue:
I enabled my GNS3VM for WebUI access via HTTPS protocol. However, with this setup, I lost access to packet capture via Wireshark. When I start capturing packets from a link and click "Start Wireshark" to open the application in Wireshark, the following message appears in the WebClient: "Error while connecting to PCAP stream: Connection closed." If you have a solution to this issue, I would appreciate it. Sincerely.
![image](https://github.com/GNS3/gns3-webclient-pack/assets/114446306/7223e323-6d80-41ba-aaca-f55457bec967)

**Comment by diniz2010** [comment]
By the way, I conducted some tests here and found that using the GNS3 GUI, packet capture and reading via Wireshark works normally with HTTPS. The error only occurs through the Web UI. With HTTP, packet capture and reading with Wireshark work fine. Thank you in advance for your help!

**Comment by diniz2010** [comment]
Greetings! Is there any solution that can be implemented to work around this issue? Thank you!

**Comment by grossmj** [comment]
> Greetings! Is there any solution that can be implemented to work around this issue? Thank you!

The current version of the webclient doesn't support HTTPS and/or authenticating with the GNS3 server. We plan to release a new version in a few days to add these missing features.

**Comment by grossmj** [comment]
@diniz2010 we have released v1.0.0b5 which should work for HTTPS.

**Comment by diniz2010** [comment]
Hello @grossmj! Thank you very much for the upload with effective functionality! It will certainly be very valuable for everyone! Thanks also for the speed in developing a solution for this! Greetings!
