### ISSUE TITLE
Error once use "wget -qO- https://raw.githubusercontent.com/GNS3/gns3-webclient-pack/master/install.sh | sh" 

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-webclient-pack#4]
Once use "wget -qO- https://raw.githubusercontent.com/GNS3/gns3-webclient-pack/master/install.sh | sh" install gns3-webclient-pack on Lubuntu 18.04.3
will show error message:
sh: 26: [[: not found
sh: 29: [[: not found
Sorry, your Linux distribution is not supported

then change sh to bash , it is working ,but after a while 

The error message appeard like below:

![image](https://user-images.githubusercontent.com/9411604/68970493-58cd9600-0822-11ea-97e8-5f23abfc2809.png)

after google a while I found this page : 
https://stackoverflow.com/questions/42530309/no-such-file-requirements-txt-error-while-installing-quartz-module

I edited the setup.py as above page finally working,
so mostly in gns3_webclient_pack.egg-info/setup.py 
line 35: **install_requires=open("requirements.txt", "r").read().splitlines(),**
shoule be: **install_requires=open("gns3_webclient_pack.egg-info/requires.txt", "r").read().splitlines(),**

**Comment by cristian-ciobanu** [comment]
Encountered same error. Installation package for gns3-webclient-pack is broken.
Tried using pip and wget installer and both failed every time with the error in the above screenshot.

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-webclient-pack/commit/fbab4b913149410d9cc3a38eb25c2ad21fed28e2
