### ISSUE TITLE
Loading Chunk Failed

### ISSUE THREAD

**Issue by blgram** [GNS3/gns3-webclient-pack#42]
I have upgraded to 2.2.47. I get error "loading chunk 26 failed" error when I launch GNS3 Web. Everything works ok, but I don't know what's this error about and how to fix it. GNS VM is installed on Server. 
![Screenshot 2024-05-18 185313](https://github.com/GNS3/gns3-webclient-pack/assets/13788706/b966fe65-1b33-4048-8d49-c937a1c047de)

**Comment by grossmj** [comment]
@blgram thanks for the report. What browser do you use and what action leads to this error? (for example, when opening a project etc.)

**Comment by blgram** [comment]
> @blgram thanks for the report. What browser do you use and what action leads to this error? (for example, when opening a project etc.)

I guess the problem resolved, it occurred on Firefox when I launch a project. Then I proceed to delete the project and created another one but It persisted. Thus, I tried Edge, and I didn't get the error on Edge. Now It seems, I don't get the warning on Firefox also.
