### ISSUE TITLE
Issue loading GNS3 Web Gui

### ISSUE THREAD

**Issue by ms-gns3** [GNS3/gns3-webclient-pack#7]
Hi

I installed the Web client pack sucessfully, launched the app, was prompted with the default application paths for Telnet/VNC etc. After I click apply and close nothing happens?

As per the guide screenshots I put the following URL into my web browser 127.0.0.1:3081/static/web-ui/ - page cannot be displayed.

I have also tried to telnet 127.0.0.1 port 3081 - port not open/listening

I do have the GNS3 VM running during these tests.

![GNS3 error](https://user-images.githubusercontent.com/63494432/79039401-f615d600-7bd8-11ea-8381-d8e19fc81939.jpg)
I found the gns3-webclient-launcher.exe in the program files folder under GNS3 WebClient Pack. I try to launch and get the following error:

cx_Freeze: Application Terminated
usage: C:\Program Files\GNS3 WebClient pack\gns3-webclient-launcher.exe

**Comment by grossmj** [comment]
You need to find the IP address for the GNS3 VM, then use IP:3080 in a browser like Chrome. From there, use the web interface to create a new project with nodes. Then your Telnet application will be launched if you start a new console to a node.

Please see the official documentation how to use console applications with the GNS3 web interface: https://docs.gns3.com/1hg1QeVk7yaaGSa6hvu6YVzM-aHWHU4ZJkeziPOPte78/index.html

**Comment by ms-gns3** [comment]
Hi, 

After further investigation I found the issue causing the Web GUI not working. FYI - I ended up downloading the latest VM and migrating my devices/ projects to the new version. After this it started working. 

Thank you for responding to me in this issue. 
All the best!
