### ISSUE TITLE
Issue with Ubuntu LTS 20.04

### ISSUE THREAD

**Issue by brightmaraba** [GNS3/gns3-webclient-pack#8]
The installation script does not work with Ubuntu LTS 20.04.
The error shown is "Sorry, your Linux Distribution is not supported".

**Comment by grossmj** [comment]
:+1: we going to fix this soon.

**Comment by brightmaraba** [comment]
Thank You! Beautiful work you guys are doing!

**Comment by grossmj** [comment]
@brightmaraba Thanks :)

Please try to install lsb-release using `sudo apt-get install lsb-release` then run the script again.

**Comment by grossmj** [comment]
Also, what do you see if you type `cat /etc/os-release`?

Thanks.

**Comment by julien-duponchelle** [comment]
```bash
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by brightmaraba** [comment]
1. lsb-realease is already the newest version (11.1.0.0ubuntu2)
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by grossmj** [comment]
@brightmaraba we have fixed the problem. Please let me know if you still get an issue.

**Comment by brightmaraba** [comment]
It works perfect, thanks!
